//! Fine-Tune Orchestrator — LoRA fine-tuning via llama.cpp
//!
//! Manages the pipeline for fine-tuning LLMs using the training data
//! generated by the Bayesian Teaching simulator. Uses llama.cpp's
//! native fine-tuning capabilities (llama-finetune binary).
//!
//! Architecture:
//! 1. Generate training data → JSONL (handled by training_data.rs)
//! 2. Convert to llama.cpp format
//! 3. Launch llama-finetune process
//! 4. Monitor progress
//! 5. Validate output LoRA adapter

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

// ═══════════════════════════════════════════════════════════════════
// Fine-Tune Configuration
// ═══════════════════════════════════════════════════════════════════

/// Hardware tier for fine-tuning, determines quantization and batch size.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum HardwareTier {
    /// Server with 2×24GB GPUs (e.g., RTX 3090/4090)
    ServerDual24GB,
    /// Single 24GB GPU
    Server24GB,
    /// Laptop with 6GB VRAM
    Laptop6GB,
    /// CPU only (very slow, for testing)
    CpuOnly,
}

impl HardwareTier {
    /// Recommended batch size for this tier.
    pub fn batch_size(&self) -> usize {
        match self {
            HardwareTier::ServerDual24GB => 8,
            HardwareTier::Server24GB => 4,
            HardwareTier::Laptop6GB => 1,
            HardwareTier::CpuOnly => 1,
        }
    }

    /// Recommended LoRA rank for this tier.
    pub fn lora_rank(&self) -> usize {
        match self {
            HardwareTier::ServerDual24GB => 64,
            HardwareTier::Server24GB => 32,
            HardwareTier::Laptop6GB => 8,
            HardwareTier::CpuOnly => 4,
        }
    }

    /// Recommended quantization level for base model.
    pub fn quantization(&self) -> &str {
        match self {
            HardwareTier::ServerDual24GB => "Q8_0",
            HardwareTier::Server24GB => "Q6_K",
            HardwareTier::Laptop6GB => "Q4_K_M",
            HardwareTier::CpuOnly => "Q2_K",
        }
    }

    /// Recommended context length.
    pub fn context_length(&self) -> usize {
        match self {
            HardwareTier::ServerDual24GB => 4096,
            HardwareTier::Server24GB => 2048,
            HardwareTier::Laptop6GB => 1024,
            HardwareTier::CpuOnly => 512,
        }
    }
}

/// Full fine-tuning configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FineTuneConfig {
    /// Path to the base GGUF model file
    pub base_model_path: PathBuf,
    /// Path to the training data JSONL file
    pub training_data_path: PathBuf,
    /// Output path for the LoRA adapter
    pub output_adapter_path: PathBuf,
    /// Hardware tier (auto-detected or specified)
    pub hardware: HardwareTier,
    /// Number of training epochs
    pub epochs: usize,
    /// Learning rate
    pub learning_rate: f64,
    /// LoRA rank (override, or use hardware tier default)
    pub lora_rank: Option<usize>,
    /// LoRA alpha (scaling factor, typically 2× rank)
    pub lora_alpha: Option<usize>,
    /// Batch size (override, or use hardware tier default)
    pub batch_size: Option<usize>,
    /// Number of training examples (for progress tracking)
    pub n_examples: usize,
}

impl FineTuneConfig {
    /// Create a config with sensible defaults for a given hardware tier.
    pub fn for_tier(tier: HardwareTier) -> Self {
        Self {
            base_model_path: PathBuf::from("/home/paulo/Programs/apps/OS/models/base.gguf"),
            training_data_path: PathBuf::from("/tmp/bayesian_training.jsonl"),
            output_adapter_path: PathBuf::from(
                "/home/paulo/Programs/apps/OS/models/bayesian-lora.gguf",
            ),
            hardware: tier,
            epochs: 3,
            learning_rate: 1e-4,
            lora_rank: None,
            lora_alpha: None,
            batch_size: None,
            n_examples: 0,
        }
    }

    /// Effective LoRA rank (config override or hardware default).
    pub fn effective_rank(&self) -> usize {
        self.lora_rank.unwrap_or_else(|| self.hardware.lora_rank())
    }

    /// Effective LoRA alpha.
    pub fn effective_alpha(&self) -> usize {
        self.lora_alpha.unwrap_or(self.effective_rank() * 2)
    }

    /// Effective batch size.
    pub fn effective_batch_size(&self) -> usize {
        self.batch_size
            .unwrap_or_else(|| self.hardware.batch_size())
    }
}

// ═══════════════════════════════════════════════════════════════════
// Fine-Tune Job
// ═══════════════════════════════════════════════════════════════════

/// Status of a fine-tuning job.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum JobStatus {
    Pending,
    Running {
        progress_pct: f64,
        current_epoch: usize,
    },
    Completed {
        adapter_path: String,
        final_loss: f64,
    },
    Failed {
        error: String,
    },
}

/// A fine-tuning job descriptor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FineTuneJob {
    pub id: String,
    pub config: FineTuneConfig,
    pub status: JobStatus,
    /// The llama-finetune command that would be executed
    pub command: String,
}

impl FineTuneJob {
    /// Build the llama-finetune command line.
    fn build_command(config: &FineTuneConfig) -> String {
        format!(
            "llama-finetune \
             --model-base {} \
             --train-data {} \
             --lora-out {} \
             --lora-r {} \
             --lora-alpha {} \
             --batch {} \
             --ctx {} \
             --epochs {} \
             --adam-lr {} \
             --threads 8",
            config.base_model_path.display(),
            config.training_data_path.display(),
            config.output_adapter_path.display(),
            config.effective_rank(),
            config.effective_alpha(),
            config.effective_batch_size(),
            config.hardware.context_length(),
            config.epochs,
            config.learning_rate,
        )
    }

    /// Create a new job from config (does not start it).
    pub fn new(config: FineTuneConfig) -> Self {
        let command = Self::build_command(&config);
        let id = format!(
            "ft-{}-{}",
            chrono_lite_timestamp(),
            config.hardware.quantization()
        );
        Self {
            id,
            config,
            status: JobStatus::Pending,
            command,
        }
    }

    /// Validate that all prerequisites exist before launching.
    pub fn validate(&self) -> Result<(), String> {
        if !self.config.base_model_path.exists() {
            return Err(format!(
                "Base model not found: {}",
                self.config.base_model_path.display()
            ));
        }
        if !self.config.training_data_path.exists() {
            return Err(format!(
                "Training data not found: {}",
                self.config.training_data_path.display()
            ));
        }
        if self.config.n_examples == 0 {
            return Err("No training examples specified".to_string());
        }
        Ok(())
    }

    /// Get estimated training time in minutes.
    pub fn estimated_time_minutes(&self) -> f64 {
        let examples_per_epoch = self.config.n_examples as f64;
        let total_steps = examples_per_epoch * self.config.epochs as f64
            / self.config.effective_batch_size() as f64;

        // Rough estimates per step based on hardware
        let secs_per_step = match self.config.hardware {
            HardwareTier::ServerDual24GB => 0.5,
            HardwareTier::Server24GB => 1.0,
            HardwareTier::Laptop6GB => 5.0,
            HardwareTier::CpuOnly => 30.0,
        };

        (total_steps * secs_per_step) / 60.0
    }
}

/// Simple timestamp without chrono dependency.
fn chrono_lite_timestamp() -> String {
    let epoch = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    format!("{}", epoch.as_secs())
}

// ═══════════════════════════════════════════════════════════════════
// Pipeline — end-to-end orchestration
// ═══════════════════════════════════════════════════════════════════

/// Run the complete teaching pipeline (dry run — shows what would happen).
pub fn plan_pipeline(
    domain_name: &str,
    n_users: usize,
    n_rounds: usize,
    tier: HardwareTier,
) -> String {
    let total_examples = n_users * n_rounds;
    let config = FineTuneConfig {
        n_examples: total_examples,
        ..FineTuneConfig::for_tier(tier)
    };
    let job = FineTuneJob::new(config);

    format!(
        "═══ Bayesian Teaching Pipeline Plan ═══\n\
         Domain:          {}\n\
         Synthetic users: {}\n\
         Rounds/user:     {}\n\
         Total examples:  {}\n\
         Hardware tier:   {:?}\n\
         LoRA rank:       {}\n\
         Batch size:      {}\n\
         Quantization:    {}\n\
         Est. time:       {:.1} min\n\
         \n\
         Command:\n  {}\n",
        domain_name,
        n_users,
        n_rounds,
        total_examples,
        job.config.hardware,
        job.config.effective_rank(),
        job.config.effective_batch_size(),
        job.config.hardware.quantization(),
        job.estimated_time_minutes(),
        job.command,
    )
}

// ═══════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hardware_tiers() {
        assert_eq!(HardwareTier::ServerDual24GB.batch_size(), 8);
        assert_eq!(HardwareTier::Laptop6GB.batch_size(), 1);
        assert_eq!(HardwareTier::Server24GB.lora_rank(), 32);
        assert_eq!(HardwareTier::CpuOnly.quantization(), "Q2_K");
    }

    #[test]
    fn test_config_defaults() {
        let config = FineTuneConfig::for_tier(HardwareTier::Server24GB);
        assert_eq!(config.effective_rank(), 32);
        assert_eq!(config.effective_alpha(), 64);
        assert_eq!(config.effective_batch_size(), 4);
    }

    #[test]
    fn test_config_overrides() {
        let mut config = FineTuneConfig::for_tier(HardwareTier::Laptop6GB);
        config.lora_rank = Some(16);
        config.batch_size = Some(2);
        assert_eq!(config.effective_rank(), 16);
        assert_eq!(config.effective_batch_size(), 2);
    }

    #[test]
    fn test_job_creation() {
        let config = FineTuneConfig::for_tier(HardwareTier::Server24GB);
        let job = FineTuneJob::new(config);
        assert!(matches!(job.status, JobStatus::Pending));
        assert!(job.command.contains("llama-finetune"));
        assert!(job.command.contains("--lora-r 32"));
    }

    #[test]
    fn test_job_validation_missing_model() {
        let config = FineTuneConfig {
            base_model_path: PathBuf::from("/nonexistent/model.gguf"),
            n_examples: 100,
            ..FineTuneConfig::for_tier(HardwareTier::CpuOnly)
        };
        let job = FineTuneJob::new(config);
        assert!(job.validate().is_err());
    }

    #[test]
    fn test_estimated_time() {
        let config = FineTuneConfig {
            n_examples: 500,
            ..FineTuneConfig::for_tier(HardwareTier::Server24GB)
        };
        let job = FineTuneJob::new(config);
        let time = job.estimated_time_minutes();
        assert!(time > 0.0, "Estimated time should be positive");
        assert!(time < 1000.0, "Estimated time should be reasonable");
    }

    #[test]
    fn test_pipeline_plan() {
        let plan = plan_pipeline("flights", 100, 5, HardwareTier::Server24GB);
        assert!(plan.contains("flights"));
        assert!(plan.contains("500")); // 100 × 5
        assert!(plan.contains("llama-finetune"));
    }

    #[test]
    fn test_job_serialization() {
        let config = FineTuneConfig::for_tier(HardwareTier::Laptop6GB);
        let job = FineTuneJob::new(config);
        let json = serde_json::to_string(&job).unwrap();
        let restored: FineTuneJob = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.status, job.status);
        assert!(restored.command.contains("llama-finetune"));
    }
}
